apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-git-config
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/anirvanr/argo-demo.git
        revision: main
        files:
        - path: "argo-appset/**/config.yaml"
  template:
    metadata:
      name: '{{name}}-{{namespace}}'
    spec:
      project: default
      sources:
        - repoURL: '{{repo}}'
          targetRevision: '{{version}}'
          chart: '{{name}}'
          helm:
            releaseName: '{{name}}'
            valueFiles:
            - $values/argo-appset/{{namespace}}/{{name}}/values.yaml
        - repoURL: 'https://github.com/anirvanr/argo-demo.git'
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
