[
  {
    "name": "ingress-nginx",
    "repo": "https://kubernetes.github.io/ingress-nginx",
    "version": "4.6.0",
    "namespace": "staging"
  },
  {
    "name": "redis",
    "repo": "https://charts.bitnami.com/bitnami",
    "version": "17.9.5",
    "namespace": "staging"
  }
]